services:
  qr-scanner:
    build:
      context: .
      dockerfile: Dockerfile      
    # platform: linux/arm64
    container_name: qr-scanner-service
    privileged: true
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/vchiq:/dev/vchiq"
    volumes:
      - /opt/vc/lib:/opt/vc/lib
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"